class AddLogIdWithIdentityToTLogDat < ActiveRecord::Migration
  def self.up
    execute "ALTER TABLE T_LOG_DAT ADD LogId INT IDENTITY(1,1)"

    execute "ALTER TABLE T_LOG_DAT DROP CONSTRAINT PK_T_LOG_DAT"

    execute "ALTER TABLE T_LOG_DAT ADD CONSTRAINT PK_T_LOG_DAT PRIMARY KEY CLUSTERED
(
	LogType ASC,
	OccDate ASC,
	LogId	ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]"
  end

  def self.down

    execute "ALTER TABLE T_LOG_DAT DROP CONSTRAINT PK_T_LOG_DAT"

    execute "ALTER TABLE T_LOG_DAT ADD CONSTRAINT PK_T_LOG_DAT PRIMARY KEY CLUSTERED
(
	LogType ASC,
	OccDate ASC

)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]"
    remove_column "T_LOG_DAT", :LogId
  end
end
