USE [master]
GO

/****** Object:  Database [RT50BodyShop]    Script Date: 08/06/2010 15:03:01 ******/
CREATE DATABASE [RT50BodyShop] ON  PRIMARY 
( NAME = N'RT50BodyShop', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\RT50BodyShop.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RT50BodyShop_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\RT50BodyShop_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RT50BodyShop] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RT50BodyShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RT50BodyShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RT50BodyShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RT50BodyShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RT50BodyShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RT50BodyShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [RT50BodyShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RT50BodyShop] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RT50BodyShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RT50BodyShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RT50BodyShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RT50BodyShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RT50BodyShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RT50BodyShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RT50BodyShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RT50BodyShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RT50BodyShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RT50BodyShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RT50BodyShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RT50BodyShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RT50BodyShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RT50BodyShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RT50BodyShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RT50BodyShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RT50BodyShop] SET  READ_WRITE 
GO

ALTER DATABASE [RT50BodyShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RT50BodyShop] SET  MULTI_USER 
GO

ALTER DATABASE [RT50BodyShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RT50BodyShop] SET DB_CHAINING OFF 
GO

